# ./.github/actions/setup-development-environment/action.yml
name: "Setup Development Environment"

inputs:
  google-services:
    description: 'Google Services Json'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Create google-services.json
      shell: bash
      run: echo -n "${{ inputs.google-services }}" | base64 --decode > ./app/google-services.json
