name: "[CD] Generate Release Notes"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
            
      - name: Get App Version
        id: get-app-version
        uses: ./.github/actions/get-app-version

      - name: Create Release
        run: |
          tag_name=${{ steps.get-app-version.outputs.version_code }}
          name=${{ steps.get-app-version.outputs.version_name }}

          RESPONSE=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{\"tag_name\":\"$tag_name\",\"target_commitish\":\"main\",\"name\":\"$name\",\"generate_release_notes\":true}" \
            -w "\n%{http_code}" -o -)

          RESPONSE_BODY=$(echo "$RESPONSE" | head -n -1)
          RESPONSE_CODE=$(echo "$RESPONSE" | tail -n 1)

          echo "Response Code: $RESPONSE_CODE"
          echo "Response Body: $RESPONSE_BODY"

          if [ "$RESPONSE_CODE" -lt 200 ] || [ "$RESPONSE_CODE" -gt 299 ]; then
            exit 1
          fi

      - name: Close Milestone
        shell: bash
        run: |
          # 마일스톤 이름으로 MILESTONE_NUMBER 얻기
          MILESTONE_NUMBER=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/milestones" | \
          jq -r --arg MILESTONE_NAME "${{ steps.get-app-version.outputs.version_name }}" '.[] | select(.title == $MILESTONE_NAME) | .number')
  
          # 해당 MILESTONE_NUMBER로 마일스톤 닫기
          if [ ! -z "$MILESTONE_NUMBER" ]; then
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/milestones/$MILESTONE_NUMBER" \
              -d '{"state": "closed"}'
          else
            echo "Milestone not found"
          fi
